### ISSUE TITLE
Window size and dock positioning is 1 pixel off

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#288]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10
**CEmu version:** CEmu v1.1.1 (git: 11df959) 
**Describe your issue:**  
Window size and dock positioning is 1 pixel off at each new start  

What are the steps to reproduce this issue?
-------------------------------------------
1. Arrange your CEmu a TI 84 emulator, with only screen and keypad (80% size or 75% size)
2. Save calculator state and close the app
3.Restart the app an notice the keypad dock is 1 pixel off position and hence the window is 1 pixel wider showing white lines left of the keypad and richt of the screen

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
See attached screen captures
![snipaste_2018-10-16_07-29-27](https://user-images.githubusercontent.com/10008599/46994821-4c09da80-d116-11e8-8035-c94e80905e9d.png)
![snipaste_2018-10-16_07-29-56](https://user-images.githubusercontent.com/10008599/46994822-4ca27100-d116-11e8-83f9-88de0c1d924f.png)

**Comment by adriweb** [comment]
It's hard to fix and it may simply be a bug in Qt. AFAIK, we don't really have an ETA for a fix, sorry...

BTW:
```
11:24:41 <@jacobly> also, that's way more than one pixel
11:24:48 <@MateoC> I know what causes it
11:24:54 <@MateoC> If that helps
11:25:14 <@MateoC> It's the dumb dock central divider 
11:26:09 <@MateoC> It should never be shown if edit mode is disabled, but for some reason it is
```

**Comment by mateoconlechuga** [comment]
I believe this has been fixed in the latest development build. (tested on windows 10). Let us know if you have any other issues.

**Comment by Stephan-P** [comment]
This issue is still in Jacobly's latest build
![image](https://user-images.githubusercontent.com/10008599/49140649-17806580-f2f5-11e8-929d-d716f487ee86.png)

**Comment by mateoconlechuga** [comment]
I have no idea how to reproduce this because it doesn't happen for me.

**Comment by runer112** [comment]
I can't reproduce this, either (v1.2dev, git: e4545c9):

![cemu64_2018-11-28_10-30-03](https://user-images.githubusercontent.com/6608979/49162361-b6f32780-f2f8-11e8-9991-399e42c8e790.png)

**Comment by mateoconlechuga** [comment]
Perhaps an outdated config is messing things up. Try using `Extras > Reset CEmu`, and then starting from scratch.

**Comment by runer112** [comment]
Silly question, but can you just drag the right edge of the window and make it smaller, thus eliminating the white space?

**Comment by Stephan-P** [comment]
Yes, something IS in the .cemu.
I setup my TI-84 emulator as I like it and then exported a bootable rom.

I then wiped the config.ini and .ce file from c:\program files\cemu, as well as did I wipe c:\Users\username\Appdata\cemu-dev.

I then started cemu again and Lo and Behold, Cemu started with the proper ROM and the window settings I prefer: LCD screen + keypad only. No initial welcome, no settings window.
The keypad windows DOES have its 2 pixel offset again, I'm sorry to tell.
Just to be complete: C:\Program Files\Cemu now contains a file cemu-image.ce. No config.ini.
C:\users\username\local\cemu-dev\ has been created again, including config.ini and cemu_rom.rom.
Closing CEmu and restarting it again gives me the same setup, including 2pix offset.

Another thing, was it not the plan to suppress or at least minimize the Windows Console during CEmu startup?

**Comment by runer112** [comment]
Also, does this problem occur at other scale factors? I'd be interested to see if it goes away at a larger scale like 80% (or normal 100%), or if it gets worse at a smaller scale like 60%.

**Comment by Stephan-P** [comment]
> Silly question, but can you just drag the right edge of the window and make it smaller, thus eliminating the white space?

Yes, I can take the window side and reduce its width so that the 2pix offset is gone.
After closing CEmu and restarting it the 2pix offset for the keypad is back again.

**Comment by adriweb** [comment]
> I then started cemu again and Lo and Behold, Cemu started with the proper ROM and the window settings I prefer: LCD screen + keypad only. No initial welcome, no settings window.

Correctly handling multiple configs, including portable ones, is hard ; these kinds of issues might never be fully solved :P

> Another thing, was it not the plan to suppress or at least minimize the Windows Console during CEmu startup?

That's actually a setting (for Windows builds) if I remember correctly - what if you toggle it, is it gone or still there on the next restart?

**Comment by runer112** [comment]
Whoops, I just skimmed the issue originally and didn't pick up on the fact that the positioning gets messed up only after a restart. Yeah, I can totally reproduce that. CEmu definitely has some issue that pushes docks around a tiny bit (usually making them slightly bigger) on startup.

**Comment by mateoconlechuga** [comment]
Did you place a config file next to CEmu. Because it won't work if you have an old one.

**Comment by Stephan-P** [comment]
> Also, does this problem occur at other scale factors? I'd be interested to see if it goes away at a larger scale like 80% (or normal 100%), or if it gets worse at a smaller scale like 60%.

Unfortunately, I cannot try this with a higher screen scale.
When I set the screen scale to 80% and adjust the height of the window, I can only extend to a certain point, not far enough so that the keypad width corresponds with the LCD-width.
My work notebook is only 1366x768 and only at 70% will LCD and keypad fit the screen height.
Can it be that the max height of the CEmu window is limited to the screen height?

At a smaller scale (60%) the keypad also receives its 1-2 pixel offset.

**Comment by Stephan-P** [comment]
> That's actually a setting (for Windows builds) if I remember correctly - what if you toggle it, is it gone or still there on the next restart?

I enabled the Windows console, reduced to a really small size AND positioned it underneath the CEmu window. Then I disabled it again. Upon the next start, the Windows console window opened in full size again, not under the CEmu window.

**Comment by adriweb** [comment]
> > That's actually a setting (for Windows builds) if I remember correctly - what if you toggle it, is it gone or still there on the next restart?
> 
> I enabled the Windows console, reduced to a really small size AND positioned it underneath the CEmu window. Then I disabled it again. Upon the next start, the Windows console window opened in full size again, not under the CEmu window.

Alright, that might be a bug for @alberthdev then. That said, I'm wondering if it's build-specific too (maybe not there for release versions?)

**Comment by Stephan-P** [comment]
> Whoops, I just skimmed the issue originally ...

When I write a substantial story, it's usually worth reading all of it ;-)
Sorry

**Comment by runer112** [comment]
Through some discussion on IRC, we're pretty sure we pinpointed the cause of the issue. It's a result of part of UI edit mode sneaking its way into the layout on startup even if you have UI edit mode disabled.

We're not sure how to fix it (yet).

**Comment by adriweb** [comment]
... and apparently something related to the central widget spacer. It looks indeed like a pain to fix considering what we've tried already.

**Comment by Stephan-P** [comment]
Yeah, it does look like the LCD screen is positioned left aligned, wheras the Keypad is positioned at the center. Mix in some clever maths and rounding and the necessary window width needs some upward adjustment and the gap is created.

**Comment by mateoconlechuga** [comment]
I deleted the line that fixed it. Can someone add it back in:

https://github.com/CE-Programming/CEmu/commit/155f1eba0ad517c20c1b04467feb0435575eed02#diff-ef62af2c016b9e0bc79e7a0a752151e8L71

**Comment by adriweb** [comment]
Well, my commit closed the issue but I guess you can wait for a few minutes and try jacobly's build again.

**Comment by runer112** [comment]
Yup, looks like that fixed it to me.

**Comment by Stephan-P** [comment]
Dito. It looks like this morning's download of Jacobly's build does away with the pixel offset.
Keypad is properly aligned with LCD now. I'm very happy.
