### ISSUE TITLE
Can't run TI-83 Premium CE ROM

### ISSUE THREAD

**Issue by zdimension** [CE-Programming/CEmu#39]
I used the ROM dumping wizard to get the rom of my (real) TI-83 Premium CE calculator, but at the end of the wizard it started CEmu with the freshly-created ROM, but it shown the console window and then "CEmu has stopped working". And if now I start CEmu, click Browse and choose the .rom file, it says "Invalid ROM image".
Also, the dump program created 12 RomData variables (from A to L) but the wizard only takes 11 (at K the progress bar is full). It may be related.

**Comment by MateoConLechuga** [comment]
Try transferring the K RomData variable first. Also, would you mind posting your BOOT and BASE code versions? This can be found by pressing [mode]+[alpha]+[ln]. Thanks for your help!

**Comment by zdimension** [comment]
I tried with K first, still "CEmu has stopped working", and the [mode]+[alpha]+[ln] doesn't do anything (it only shows the Mode menu when I press [mode], and I tried pressing [alpha] or [ln] first, nothing happens)

**Comment by adriweb** [comment]
For the ROM Wizard, are you able to select all the files at once? I believe that worked for me.
For the boot versions, make sure you're at the Home screen first, then press sequentially, without holding the keys, [mode], then [alpha], then [ln]. It should display the two version numbers. You can press [clear] to exit that screen.

**Comment by zdimension** [comment]
Yes, I can select all files at once, but it still crashes at start. And for the version number stuff, when I press [mode], the Mode menu shows up, when I press [alpha], the little alpha icon shows up at upper right corner of the screen, and when I press [ln] it goes back to the home screen and types `ln(`.

**Comment by MateoConLechuga** [comment]
Under the About menu on the memory management screen, what OS version are
you running?

**Comment by adriweb** [comment]
OK, that's just weird...

Another idea: open TI-Connect CE on your computer, plug your calculator, go to the second sidebar tab to the left ("Calculator Explorer"), and right-click on your calculator, then press Calculator Information.
In the window that will pop up, please tell us the things there :) (Or you can make a screenshot if you want)

Yet another idea would be to press [2nd] then [+] on your calculator, then go into the "About" / "A propos" menu, and tell us what OS version it is (but more info given by TI Connect would be useful)

**Comment by zdimension** [comment]
I'm running the latest one, 5.1.5.
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/4533568/13472238/4427fe64-e0b4-11e5-8c1d-7cb462f9170e.png)

**Comment by adriweb** [comment]
OK, so, it appears I have exactly the same configuration as yours...
On the back of the calculator, does the serial number part say `L-0215A` or something like that?

**Comment by MateoConLechuga** [comment]
Also, what does it say in the console window? That is also very helpful :)

**Comment by zdimension** [comment]
@adriweb The full number is `1036005108 L-0315A`
@MateoConLechuga Nothing shows up in the console window when the wizard finishes (when it auto-loads the ROM) and when I restart CEmu to load the rom manually, it says "Invalid ROM".

**Comment by adriweb** [comment]
What is the "Prod #" in the About menu in the calculator ([2nd][+][2]) ?
Both my 83 Premium CE and 84 Plus CE show 13-07-05-1300...

**Comment by zdimension** [comment]
I get 13-07-05-1300 too.

**Comment by adriweb** [comment]
I'm starting to wonder if it's a CEmu build issue (Mac/Windows difference somewhere)... Because the ROM dump is working fine for me... (I'm on Mac).
But I believe @MateoConLechuga is redoing some of the CEmu-side of the ROM dumping part, so maybe that'll work better for you when it's done

**Comment by MateoConLechuga** [comment]
I committed a1163cc,which will hopefully fix the issue. If you would be so kind, please test using the 2016-03-03.zip build when it comes out. Thanks! (build is found here:) http://pimathbrainiac.me/CEmu/

**Comment by JaroslavN** [comment]
i think it doesn't work because of 5.1.5 or not?

**Comment by zdimension** [comment]
I can send you the ROMData* files I got from my calculator if you want to test them.

**Comment by adriweb** [comment]
@JaroslavN No, it works fine for me
@zdimension I edited your message - we got the content and will look into it :)

**Comment by MateoConLechuga** [comment]
The latest build (03-03.zip) is available here: http://pimathbrainiac.me/CEmu/
The issue should be solved by sending the dumping program and following the onscreen instructions. Thanks!

**Comment by zdimension** [comment]
Still crashes... also why do I still get 12 RomData* variables while CEmu still takes only 11?

**Comment by MateoConLechuga** [comment]
You didn't download the latest release and rerun the dumper program like I just asked.

**Comment by MateoConLechuga** [comment]
Wait, what? Why is the build not updated.

**Comment by zdimension** [comment]
Yay, it works!

**Comment by MateoConLechuga** [comment]
Cool :) Not currently, because emulating USB support is still an open issue, as is the TI-83PCE keypad design. Hopefully it won't be too much longer though :)
